name: test

on:
  push:
  pull_request:

jobs:
  suite:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Versions
        run: bash --version | head -1; git --version; which bash
      - name: gpm suite
        run: python tests/test_gpm.py
